//@ui5-bundle zchatbot/Component-preload.js
sap.ui.require.preload({
	"zchatbot/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","zchatbot/model/models"],function(t,e,a){"use strict";return t.extend("zchatbot.Component",{metadata:{manifest:"json"},init:function(){t.prototype.init.apply(this,arguments);var e=new sap.ui.model.odata.v2.ODataModel("/sap/opu/odata/scwm/WI_INTEGRATION_SRV/");this.setModel(e);var l=document.createElement("script");l.src="https://cdn.cai.tools.sap/webclient/bootstrap.js";l.setAttribute("data-channel-id","bcacaa43-3e97-4928-bcce-abbf68731012");l.setAttribute("data-token","7de4d5a0cb5b6a3cc0fb0c65ca48d256");l.setAttribute("data-expander-type","CAI");l.setAttribute("data-expander-preferences","JTdCJTIyYWNjZW50Q29sb3IlMjIlM0ElMjIlMjMwZjAwYTAlMjIlMkMlMjJiYWNrZ3JvdW5kQ29sb3IlMjIlM0ElMjIlMjNjN2NjZjElMjIlMkMlMjJjb21wbGVtZW50YXJ5Q29sb3IlMjIlM0ElMjIlMjNmZWZlZmUlMjIlMkMlMjJleHBhbmRlckxvZ28lMjIlM0ElMjJodHRwcyUzQSUyRiUyRmxvZ29kaXguY29tJTJGbG9nbyUyRjIxNDE2NTcuanBnJTIyJTJDJTIyZXhwYW5kZXJUaXRsZSUyMiUzQSUyMiUyMiUyQyUyMm9uYm9hcmRpbmdNZXNzYWdlJTIyJTNBJTIySGVyZSUyMHRvJTIwQXNzaXN0JTIyJTJDJTIyb3BlbmluZ1R5cGUlMjIlM0ElMjJuZXZlciUyMiUyQyUyMnRoZW1lJTIyJTNBJTIyQ1VTVE9NJTIyJTdE");l.id="cai-webclient-custom";document.head.appendChild(l);this.getRouter().initialize();this.setModel(a.createDeviceModel(),"device")}})});
},
	"zchatbot/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("zchatbot.controller.App",{onInit:function(){}})});
},
	"zchatbot/controller/View1.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("zchatbot.controller.View1",{onInit:function(){}})});
},
	"zchatbot/i18n/i18n.properties":'# This is the resource bundle for zchatbot\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Apollo\n\n#YDES: Application description\nappDescription=An SAP Fiori application.\n#XTIT: Main view title\ntitle=Apollo\n\n#XFLD,30\nflpTitle=Apollo\n\n#XFLD,35\nflpSubtitle=Chatbot\n',
	"zchatbot/manifest.json":'{"_version":"1.42.0","sap.app":{"id":"zchatbot","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.15.2","toolsId":"39f04891-ff61-4d13-99d2-3c3bb63f2592"},"dataSources":{"mainService":{"uri":"/sap/opu/odata/scwm/WI_INTEGRATION_SRV/","type":"OData","settings":{"annotations":[],"localUri":"localService/metadata.xml","odataVersion":"2.0"}}},"crossNavigation":{"inbounds":{"ZCHATBOT-display":{"semanticObject":"ZCHATBOT","action":"display","title":"{{flpTitle}}","subTitle":"{{flpSubtitle}}","signature":{"parameters":{},"additionalParameters":"allowed"}}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.102.2","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"zchatbot.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"zchatbot.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView1","pattern":":?query:","target":["TargetView1"]}],"targets":{"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"}}},"rootView":{"viewName":"zchatbot.view.App","type":"XML","async":true,"id":"App"}}}',
	"zchatbot/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"zchatbot/view/App.view.xml":'<mvc:View controllerName="zchatbot.controller.App"\n    xmlns:html="http://www.w3.org/1999/xhtml"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><App id="app"></App></mvc:View>\n',
	"zchatbot/view/View1.view.xml":'<mvc:View controllerName="zchatbot.controller.View1"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><Page id="page" title="{i18n>title}"><content /></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
